### ISSUE TITLE
Gem requires itself

### ISSUE THREAD

**Issue by jphastings** [kookster/activemessaging#27]
Okay, so something weird is going on here. Your .gemspec has lots of commented out `#s.add_runtime_dependency(%q<activemessaging>, [">= 0"])` lines and a comment I don't quite understand about blocking the gem from installing.

Are you attempting to prevent this gem from being installed?

If so, why? If not, how can I fix it so I can install the gem?

```
$ gem install activemessaging
ERROR:  Error installing activemessaging:
    activemessaging requires activemessaging (>= 0)
```

Thanks

**Comment by Envek** [comment]
This should be already fixed in #41.

@kookster could you please publish a new release, as now it's impossible to install gem from rubygems?
