### ISSUE TITLE
Can not install and launch

### ISSUE THREAD

**Issue by Envek** [kookster/activemessaging#42]
Hello!

I'm trying to install and launch ActiveMessaging, but with no luck.

Installation from gem doesn't work (see #27 and #41). Could you please publish new version.

Installation from git checkout also fails:

```ruby
# Gemfile
gem 'activemessaging', github: 'kookster/activemessaging'
```

but after succesful `bundle install`
```
$ bundle
Fetching gem metadata from https://rubygems.org/............
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
...
Using activemessaging 0.13.0 from git://github.com/kookster/activemessaging.git (at master)
...
Bundle complete! 36 Gemfile dependencies, 91 gems now installed.
```

I'm always getting:

```
$ bundle exec rails server
Could not find activemessaging-0.13.0 in any of the sources
Run `bundle install` to install missing gems.
```

Don't ever know how to debug this. Ruby on Rails 4.2, Ruby 2.2.3.

Can you help?

**Comment by kookster** [comment]
I'll take a look when I can, I do not run it on either ror 4.2 nor ruby 2.2, so it may require some updates to get things working.

**Comment by alfredolopez-kantox** [comment]
hi!

I am getting issues as well when trying to use this gem. 

For instance, if I install version 0.13.0 from rubygems I get:
```
Your Gemfile requires gems that depend on each other, creating an infinite loop. Please remove gem 'activemessaging' and try again.
```

I changed the Gemfile to use the git repo instead. Bundler will install the gem properly, but then when I try to  use the rails generator I get the following error:
```
$ bin/rails g active_messaging:install
The gemspec at /xxx/.rvm/gems/ruby-2.1.1/bundler/gems/activemessaging-62de2f2aaeaf/activemessaging.gemspec is not valid. The validation error was 'duplicate dependency on jeweler (>= 0, development), (>= 0) use:
    add_runtime_dependency 'jeweler', '>= 0', '>= 0'
'
```

**Comment by westlakem** [comment]
@kookster Any update on running on rails 4.2 / ruby 2.2?
